export enum ContractConfigKey {
  OWNER_WALLET_KEY = 'OWNER_WALLET_PRIVATE_KEY',
  ORGANIZATION_ADDRESS = 'ORGANIZATION_CONTRACT_ADDRESS',
  CERTIFICATE_TYPE_ADDRESS = 'CERTIFICATE_TYPE_CONTRACT_ADDRESS',
  CERTIFICATE_ADDRESS = 'CERTIFICATE_CONTRACT_ADDRESS',
}
