export const WEBHOOK_CONTRACT_EVENT = 'WEBHOOK_CONTRACT_EVENT';
export const WEBHOOK_EVENT_TYPE = 'WEBHOOK_EVENT_TYPE';
export const ALCHEMY_KEY = 'ALCHEMY_KEY';
export const WEBHOOK_CONTRACT_ABI = 'WEBHOOK_CONTRACT_ABI';
