export enum OrganizationJobPrefix {
  ORGANIZATION_ADDED = "ORG_ADDED",
}

export enum CertificateTypeJobPrefix {
  CERTIFICATE_TYPE_ADDED = "CT_ADDED",
  CERTIFICATE_TYPE_UPDATED = "CT_UPDATED",
  CERTIFICATE_TYPE_DEACTIVATED = "CT_DEACTIVATED",
}